# API
api_taxonomy:
    path: /api/v{version}/taxonomy
    controller: Adshares\Adclassify\Controller\ApiController::getTaxonomy
    methods: GET
    requirements:
        version:  '0|1'

api_requests:
    path: /api/v{version}/requests
    controller: Adshares\Adclassify\Controller\ApiController::postRequests
    methods: POST
    requirements:
        version:  '0|1'

# security
security_login:
    path: /login
    controller: Adshares\Adclassify\Controller\SecurityController::login

security_logout:
    path: /logout

security_account:
    path: /account
    controller: Adshares\Adclassify\Controller\SecurityController::account

# main pages
index:
    path: /
    controller: Adshares\Adclassify\Controller\AppController::index

info:
    path: /info.{_format}
    controller: Adshares\Adclassify\Controller\AppController::info
    methods: GET
    defaults:
        _format: 'json'
    requirements:
        _format:  'json|txt'

# classification
classification_status:
    path: /classification/status
    controller: Adshares\Adclassify\Controller\ClassificationController::status

classification:
    path: /classification/{requestId}
    controller: Adshares\Adclassify\Controller\ClassificationController::index
    defaults:
        requestId: null
    requirements:
        requestId:  '\d+'

# admin page
admin:
    path: /admin
    controller: Adshares\Adclassify\Controller\AdminController::index